
package lsmichel.dev.wso2.isAdminWebserviceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OAuth2TokenValidationServicePortType", targetNamespace = "http://oauth2.identity.carbon.wso2.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OAuth2TokenValidationServicePortType {


    /**
     * 
     * @param validationReq
     * @return
     *     returns sn.atos.projet.tigo.cms.OAuth2IntrospectionResponseDTO
     */
    @WebMethod(action = "urn:buildIntrospectionResponse")
    @WebResult(targetNamespace = "http://org.apache.axis2/xsd")
    @RequestWrapper(localName = "buildIntrospectionResponse", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.BuildIntrospectionResponse")
    @ResponseWrapper(localName = "buildIntrospectionResponseResponse", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.BuildIntrospectionResponseResponse")
    public OAuth2IntrospectionResponseDTO buildIntrospectionResponse(
        @WebParam(name = "validationReq", targetNamespace = "http://org.apache.axis2/xsd")
        OAuth2TokenValidationRequestDTO validationReq);

    /**
     * 
     * @param validationReqDTO
     * @return
     *     returns sn.atos.projet.tigo.cms.OAuth2ClientApplicationDTO
     */
    @WebMethod(action = "urn:findOAuthConsumerIfTokenIsValid")
    @WebResult(targetNamespace = "http://org.apache.axis2/xsd")
    @RequestWrapper(localName = "findOAuthConsumerIfTokenIsValid", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.FindOAuthConsumerIfTokenIsValid")
    @ResponseWrapper(localName = "findOAuthConsumerIfTokenIsValidResponse", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.FindOAuthConsumerIfTokenIsValidResponse")
    public OAuth2ClientApplicationDTO findOAuthConsumerIfTokenIsValid(
        @WebParam(name = "validationReqDTO", targetNamespace = "http://org.apache.axis2/xsd")
        OAuth2TokenValidationRequestDTO validationReqDTO);

    /**
     * 
     * @param validationReqDTO
     * @return
     *     returns sn.atos.projet.tigo.cms.OAuth2TokenValidationResponseDTO
     */
    @WebMethod(action = "urn:validate")
    @WebResult(targetNamespace = "http://org.apache.axis2/xsd")
    @RequestWrapper(localName = "validate", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://org.apache.axis2/xsd", className = "sn.atos.projet.tigo.cms.ValidateResponse")
    public OAuth2TokenValidationResponseDTO validate(
        @WebParam(name = "validationReqDTO", targetNamespace = "http://org.apache.axis2/xsd")
        OAuth2TokenValidationRequestDTO validationReqDTO);

}
